name: dotnetcore

on:
  push:
    tags:
      - "Versions/*"
  workflow_dispatch:
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'RobustClipboard.sln'

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: dotnet build $SOLUTION
      
    - name: Publish to Nuget.org
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
      
    - name: Publish to Tevux Packages
      run: nuget push **\*.nupkg -Source 'https://nuget.pkg.github.com/tevux-tech/index.json' -ApiKey ${{secrets.GITHUB_TOKEN}}